base_url: http://localhost:8000/api

components:
  DataProcessor:
    functions:
      process_from_directory: internal/process_from_directory/
  
  VectorStore:
    functions:
      search: external/vector_store/search/
    requires:
      - DataProcessor

  VSManager:
    functions:
      inject_from_directory: external/vs_manager/inject_from_directory/
      add_from_directory: external/vs_manager/add_from_directory/
  
  Generator:
    functions:
      simple_generate: external/simple_generate/
  
  RAGGenerator:
    functions:
      rag: external/rag/
