base_url: http://localhost:8000/api/application

components:
  DataProcessor:
    functions:
      process_from_directory: internal/process_from_directory/
  VectorStore:
    functions:
      search: external/vector_store/search/
  VSManagerInject:
    functions:
      inject_from_directory: external/vs_manager/inject_from_directory/
  VSManagerAdd:
    functions:
      add_from_directory: external/vs_manager/add_from_directory/
  Generator:
    functions:
      simple_generate: external/simple_generate/
  RAGGenerator:
    functions:
      rag: external/rag/
