"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 2.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ---------------  SECURITY WARNING: don't run with debug turned on in production!  ---------------
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

SECRET_KEY = "r(bf&^w1id_*7l10_rxfuftv_1wmwkvu+)0t!bu5n*1@l$rs!r"

# TODO : SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
TEST_MODE = True

if DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = ["*"]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG",
    },
    "loggers": {
        # 'django': {
        #     'level': 'DEBUG',
        # },
        "rest_framework_simplejwt": {
            "level": "DEBUG",
        },
    },
}


# -------------------------------------------------------------------------------------------------


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django_extensions",
    "rest_framework",
    "rest_framework_simplejwt",
    "api_auth",
    "application",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Rest & Authentication

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
    "DEFAULT_AUTHENTICATION_CLASSES": (),
    "DEFAULT_PERMISSION_CLASSES": (),
}

ALGORITHM = "RS256"



INTERNAL_BASE_URL = (
    "http://localhost:8000/api/auth/"
    if TEST_MODE
    else ""
)

AUTH_CONFIG = {

    "S2S": {
        "sign": {
            "type": "OAUTH",
            "CLIENT_ID": "BvMidR0TCQxp5QwI4bCiv69eA5cbPdF4ArjEI0jj",
            "SECRET": (
                "vP735g66o38hhD1jsCHuLv5fQvp04TR5RQLwOy3lz8rJywToKSFQ3qgnlqpon"
                "KagWU15yP9gT8l2kq24sSLhVJOjyyg8EuzEuRNwExsnSGj3i5ZXVVSIDtCt7MxrF29H",
            ),
            "ORGANIZATION_TOKEN": (
                "866959ea84cefbc0fc185ecd124126aed8d6a4bb209a4865c28e94695db1e34d",
            ),
            "URL": "",
        },
    }
}


# -----

ROOT_URLCONF = "server.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "server.wsgi.application"

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}

